dotnet/asp-net/OnlineAssessment/Models/ErrorViewModel.cs
namespace OnlineAssessment.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

dotnet/asp-net/OnlineAssessment/Models/OnlineAssessmentContext.cs
using Microsoft.EntityFrameworkCore;
namespace OnlineAssessment.Models;

public class OnlineAssessmentContext : DbContext
{
    public OnlineAssessmentContext(DbContextOptions options)
        : base (options)
    {

    }

    public DbSet<Question> Questions { get; set; }
}

dotnet/asp-net/OnlineAssessment/Models/Question.cs
namespace OnlineAssessment.Models;

public class Question
{
    public int id { get; set; }
    public string? question { get; set; }
}

dotnet/asp-net/OnlineAssessment/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using OnlineAssessment.Models;

namespace OnlineAssessment.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

dotnet/asp-net/OnlineAssessment/Controllers/QuestionController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineAssessment.Models;

namespace OnlineAssessment.Controllers;

public class QuestionController : Controller
{
    private readonly OnlineAssessmentContext _context;

    public QuestionController(OnlineAssessmentContext context)
    {
        _context = context;
    }
    public IActionResult Index()
    {
        List<Question> questions = _context.Questions.ToList();
        return View(questions);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Create(Question ques)
    {
        _context.Questions.Add(new Question
        {
            question = ques.question
        });
        _context.SaveChanges();
        List<Question> questions = _context.Questions.ToList();
        return View("Index", questions);
    }

    public IActionResult Edit(int id)
    {
        Question question = _context.Questions.Find(id);
        return View(question);
    }

    [HttpPost]
    public IActionResult Edit(int id, Question ques)
    {
        Question question = _context.Questions.Find(id);
        question.question = ques.question;
        _context.SaveChanges();

        List<Question> questions = _context.Questions.ToList();
        return View("Index", questions);
    }

    public IActionResult Delete(int id)
    {
        Question question = _context.Questions.Find(id);
        _context.Questions.Remove(question);
        _context.SaveChanges();
        List<Question> questions = _context.Questions.ToList();
        return View("Index", questions);
    }
}

dotnet/asp-net/OnlineAssessment/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

dotnet/asp-net/OnlineAssessment/Views/Question/Create.cshtml
@model Question

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>New Question</h1>
    <form action="" method="post">
        <input type="text" asp-for="question" class="form-control"><br>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</body>
</html>

dotnet/asp-net/OnlineAssessment/Views/Question/Edit.cshtml
@model Question

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Edit Question</h1>
    <form action="" method="post">
        <input type="text" asp-for="id" value="@Model.id" readonly class="form-control mb-3">
        <input type="text" asp-for="question" value="@Model.question" class="form-control mb-3" required>
        <button class="btn btn-primary">Submit</button>
    </form>
</body>
</html>

dotnet/asp-net/OnlineAssessment/Views/Question/Index.cshtml
@model List<Question>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <h1>Questions Index</h1>
    <a asp-controller="Question" asp-action="Create" class="btn btn-primary">New Question</a>
    <table class="table">
        <tr>
            <th>Id</th>
            <th>Question</th>
            <th></th>
            <th></th>
        </tr>
        @foreach (var question in Model)
        {
            <tr>
                <td>@question.id</td>
                <td>@question.question</td>
                <td><a asp-controller="Question" asp-action="Edit" asp-route-id="@question.id">Edit</a></td>
                <td><a asp-controller="Question" asp-action="Delete" asp-route-id="@question.id">Delete</a></td>
            </tr>
        }
    </table>
</body>
</html>

dotnet/asp-net/OnlineAssessment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineAssessment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OnlineAssessment.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OnlineAssessment</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Question" asp-action="Index">Question</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - OnlineAssessment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>